---
title: "Lab 4"
author: "Sydney Mayes"
date: "2023-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(Metrics)
library(cowplot)
library(here)
library(kableExtra)

```

## Data
```{r}
load(here("data", "fish_data.Rdata"))
```

## Single model NLS

$$
S_t=B_{t+1}-B_t+C_t
$$
```{r}
surplus <- Fish_data %>% 
  group_by(stockid) %>% 
  select(stockid, year, TBbest, TCbest) %>% 
  drop_na() %>% 
  mutate(f_biomass = lead(TBbest)) %>% 
  mutate(surplus = f_biomass - TBbest + TCbest) %>% 
  drop_na()
```

```{r}
one_stock <- surplus %>% 
  filter(stockid == "COD1f-XIV")

ggplot(data = one_stock, aes(x=year, y=surplus)) +
  geom_point(size = 3, color = 'black') +
  theme_minimal()
```

## Step One: Select a model

$$
\hat{S_t}=-e*MSY(\frac{B_t}{K}\ln(\frac{B_t}{K}))
$$
```{r}
fox <- function(m, carry, biomass){
  out = -2.718*m*(biomass/carry)*log(biomass/carry)
  return(out)
  }
```

## Step Two: Initial Guess

```{r}
guess_vec = c(max(one_stock$TBbest)*3.7, 
              max(one_stock$TBbest))
```

## Step 3: Run NLS

```{r}
one_stock_nls = nls(surplus~fox(m, carry, TBbest),
                    data = one_stock, 
                    start = list(m = guess_vec[1], carry = guess_vec[2]),
                    trace = TRUE)
```
```{r}
one_stock_predict <- one_stock %>% 
  mutate(predict = predict(one_stock_nls, newdata =.))

ggplot(data=one_stock_predict) +
  geom_point(aes(x=year, y=surplus))+
  geom_point(aes(x=year, y=predict), color='red')
```
```{r}
control_nls = nls(surplus~fox(m, carry, TBbest),
                    data = one_stock, 
                    start = list(m = guess_vec[1], carry = guess_vec[2]),
                    trace = TRUE,
                  control = nls.control(tol = 2.1e-9, minFactor=1e-10,warnOnly = TRUE)) # very precise tolerance
# results add a couple more iterations but it doesn't do anything new
# got an error -- without adding the minFactor

broom::tidy(control_nls) %>% 
  kable(caption = "control NLS") %>% 
  kable_classic()

# see code key
```

## Using purrr to run many nls models

```{r}
all_nls_fcn <- function(surplus_df){
  nls(surplus~fox(m, carry, TBbest),
      data=surplus_df,
      start=list(m=max(surplus_df$TBbest)*0.37, carry=max(surplus_df$TBbest)
))
}

all_nls_fcn(one_stock)
```
```{r}
fox_all <- surplus %>% 
  group_by(stockid) %>% 
  nest() %>% 
  mutate(nls_model = map(data, ~all_nls_fcn(.x))) %>% 
  mutate(predictions = map2(nls_model, data, ~predict(.x, newdata=.y))) %>% 
  mutate(rmse=map2_dbl(predictions, data, ~rmse(.x, .y$surplus)))


```


